apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: service-nodeport-web
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30008
  selector:
    app: web
