apiVersion: v1 
kind: Service 
metadata: 
  name: hollowapp 
  labels:
    app: hollowapp 
spec:
  type: NodePort 
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30001
    protocol: TCP
  selector:
    app: hollowapp
