apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  volumes:
    - name: mysql-data
      persistentVolumeClaim:
        claimName: pvc
  containers:
  - name: mysql
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    - name: MYSQL_DATABASE
      value: "eazytraining"
    - name: MYSQL_USER
      value: "eazy"
    - name: MYSQL_PASSWORD
      value: "eazy"
    volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-data
